### ISSUE TITLE
crash with rust runtime: "Cannot read property 'pipe' of null"

### ISSUE THREAD

**Issue by dsilvasc** [softprops/serverless-localhost#13]
## 🐛 Bug description
On a project with `runtime: rust`, hitting the localhost server crashes:

```
$ serverless localhost
Serverless: Starting server...
Serverless: Listening on port 3000...
Serverless: ❯ Function routes
Serverless: * world
Serverless:     get http://localhost:3000/
Serverless: Docker image not present
Serverless: Pulling lambci/lambda:rust image...

  Type Error ---------------------------------------------

  TypeError: Cannot read property 'pipe' of null
      at Modem.followProgress (node_modules/docker-modem/lib/modem.js:319:10)
      at node_modules/serverless-localhost/src/docker.ts:36:20
      at node_modules/dockerode/lib/docker.js:119:7
      at node_modules/docker-modem/lib/modem.js:265:7
      at IncomingMessage.<anonymous> (node_modules/docker-modem/lib/modem.js:284:9)
      at IncomingMessage.emit (events.js:215:7)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I think that's because the image `lambci/lambda:rust` does not exist on docker hub.  Should that be `lambci/lambda:provided`?

The exception itself seems to come from https://github.com/apocas/docker-modem/issues/93

**Comment by y2kappa** [comment]
Did you manage to get this working? If so, did you eventually manage to get this working entirely for Rust locally?

**Comment by y2kappa** [comment]
I managed to get this working by having this locally without any changes really, just forking the original repo from softprops and then doing:
```
npm install
npm run build
npm link
cd /my/rust/lambda/app/
npm link serverless-localhost
```

Also you need to have `bootstrap` linux binary in the current folder which you can build using https://hub.docker.com/r/ekidd/rust-musl-builder/ and copying from target locally. 

```
alias rust-musl-builder='docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder'
rust-musl-builder cargo build --release
```

Also in `serverless.yml` I need to have runtime:provided for my rust function. 

This is probably too late, but lmk if you need help. Otherwise if you found a better way, I'm curious to learn.

**Comment by dsilvasc** [comment]
When I was trying serverless back in december, I didn't manage to get it working, unfortunately.
